name: Scheduled Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'  # Run at 12:55 IST (07:25 UTC)
    - cron: '00 13 * * *'  # Run at 12:55 IST (07:25 UTC)



jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install necessary dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y wget xvfb && \
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && \
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list && \
        sudo apt-get update && \
        sudo apt-get install -y google-chrome-stable && \
        wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chromedriver-linux64.zip" && \
        sudo unzip /tmp/chromedriver.zip -d /usr/local/bin && \
        sudo rm /tmp/chromedriver.zip && \
        sudo chmod +x /usr/local/bin/chromedriver-linux64/chromedriver && \
        python -m pip install --upgrade pip && \
        pip install -r .github/workflows/requirements.txt


    - name: Run pytest
      run: pytest .github/workflows/test_vue9.py
